# DEFAULT IP ADRESS, JUST ENTER YOUR IP CAM
IP_ADRESS = "192.168.1.33" # ONLY CHANGE IP ADRESS
URL_ADRESS = "http://%s:8080/shot.jpg" % IP_ADRESS

# DEFAULT USER ADMIN
ADMIN = "admin"
ADMIN_PASSWORD = "123"

# TEST USER
TEST_USER = "BIGBROTHER"
TEST_FILE = "./static/bigbrother.jpg"
